### ISSUE TITLE
ERROR : unable to execute script at line 3045.unclosed taken

### ISSUE THREAD

**Issue by Shubby98** [akhribfarouk/Lieutenant#1]
ERROR : unable to execute script at line 3045. Unclosed taken.
it showing error with this 
i m using adobe after effect cc2018
what to do 
please reply as soon as possible

**Comment by akhribfarouk** [comment]
there is no line called 3045 the script has only 1163 lines so ...

**Comment by deltocranien** [comment]
it's at the line 996 and it say "file or folder does not exist"

**Comment by akhribfarouk** [comment]
ah ok i understand ... you must download the files of the script first you may take a look at the description of that video in youtube.
https://www.youtube.com/watch?v=HgFeqoJXbgs

**Comment by bartdong** [comment]
> it's at the line 996 and it say "file or folder does not exist"

Same as this problem

**Comment by akhribfarouk** [comment]
just put the files their folder
